### ISSUE TITLE
Support for other block types than _SRC

### ISSUE THREAD

**Issue by zeltak** [unhammer/org-rich-yank#1]
Hi

thx so much for your work this is pretty epic :)

i have some small suggestions if you dont mind

1. would it be possible to pre define the type of src block before pasting? for example if i want the block to be an EXAMPLE block can i specify that before pasting (via perhaps a different command/bind or helm/ivy?)
2. can this be extended for also copting and pasting from web sources?

thx so much 

Z

**Comment by unhammer** [comment]
Hi, thanks for your suggestions, glad you like it :-) Could you please open a separate issue for `2.`? We'll handle `1.` here.

I've also wondered if that something like that would make sense. I mostly just use `#+BEGIN_SRC` myself, but e.g. if you're pasting from a `.tex` file maybe it makes more sense to use `#+BEGIN_LaTeX`, similarly `.html` and `#+BEGIN_HTML`. But for those files, it could happen automatically – less work for the user. So I think at the very least it'd be nice to have a customizable list `org-rich-yank-block-types` from major-modes to begin/end strings, defaulting to e.g. 

```
'((html-mode "#+BEGIN_HTML" "#+END_HTML")
  (latex-mode "#+BEGIN_LaTeX" "#+END_LaTeX")
  (t "#+BEGIN_SRC" "#+END_SRC"))
```
The car of each list could also be a user-defined predicate, so you could do things like
`(add-to-list 'org-rich-yank-block-types (list (lambda (b) (equal (buffer-name b) "poems.org")) "#+BEGIN_VERSE" "#+END_VERSE"))`.

But would that solve your needs? Can you describe your use-case?

**Comment by zeltak** [comment]
Hi

i was think more of pressing a hot key and have ivy/helm present a list of possible SRC language candidates, does that make any sense? :)

**Comment by unhammer** [comment]
By "SRC language candidates", do you mean `{BEGIN_EXAMPLE, BEGIN_SRC, BEGIN_VERSE}` or `{html, LaTeX, haskell, python}`?

**Comment by zeltak** [comment]
i meant more `{html, LaTeX, haskell, python}` :)

thx alot again!

Z

**Comment by unhammer** [comment]
This *should* already happen automatically though – if you copy from a Python file, it should insert `+BEGIN_SRC python` etc. Do you have an example where that fails?

**Comment by unhammer** [comment]
If there's no known bug in source language detection and no need for other block types I'll close this :)
