### ISSUE TITLE
Lines that start with asterisk (*) can break src blocks when pasted

### ISSUE THREAD

**Issue by nickanderson** [unhammer/org-rich-yank#11]
If I yank some text while I am viewing an email in `mu4e` and any of that text has a line starting with `*` the src block pasted in `org-mode`  with `org-rich-yank` does not have those lines prefixed with `,`.

![image](https://user-images.githubusercontent.com/202896/233412394-bc8f6a40-a605-4d76-a67f-d0de4c9d5f8f.png)

For example

Say I have an email that has the following line:

```
* I added the index again.
```

If I yank it and `org-rich-yank` to paste it into `org-mode` I get something like the following:

```
#+begin_src mu4e-view
* I added the index again.
#+end_src
#+comment: Link to copy source: [[mu4e:msgid:CAGY83Edymb8HdALSHRz58-pfoMn33r5wH7Ehy_iyFrtWFvn4Yg@mail.gmail.com][Re: Accelerating a new edition of the book]]
```

That breaks the src block since the `*` is at the start of the line. Either the entire content of the src block needs to be indented one or more spaces or the line should be prefixed with `,`. 

For example:

```
#+begin_src mu4e-view
 * I added the index again.
#+end_src
#+comment: Link to copy source: [[mu4e:msgid:CAGY83Edymb8HdALSHRz58-pfoMn33r5wH7Ehy_iyFrtWFvn4Yg@mail.gmail.com][Re: Accelerating a new edition of the book]]
```

or 

```
#+begin_src mu4e-view
,* I added the index again.
#+end_src
#+comment: Link to copy source: [[mu4e:msgid:CAGY83Edymb8HdALSHRz58-pfoMn33r5wH7Ehy_iyFrtWFvn4Yg@mail.gmail.com][Re: Accelerating a new edition of the book]]
```

**Comment by unhammer** [comment]
Ooh, good catch

**Comment by nickanderson** [comment]
Tested https://github.com/unhammer/org-rich-yank/commit/9aa7fa8328c2f0737e8fad74cfaec70a42b5b36a works perfectly. 

Thanks!
:heart_eyes:
