### ISSUE TITLE
Detect and use the correct src block type when copying from src blog within org-mode

### ISSUE THREAD

**Issue by nickanderson** [unhammer/org-rich-yank#13]
It would be nice if copies from text within a src block in org mode would paste as the src block type the text came from instead of org.

For example, Say I have this text in my org file:

```
Say Hello world!

#+caption: Shell command with stderr
#+begin_src sh :results output :exports both
  echo "Hello world!"
#+end_src

#+RESULTS:
: Hello world!
```

If I select just the line `echo "Hello world!"` copy it and then paste it with `org-rich-yank` I get:

```
#+caption: Code Snippet
#+begin_src org
echo "Hello world!"
#+end_src
```

But it would be nicer if I got:

```
#+caption: Code Snippet
#+begin_src sh
echo "Hello world!"
#+end_src
```

If I select the text before the src block including the src block, then I think it makes sense to pase in org src block:

```
#+caption: Code Snippet
#+begin_src org
Say Hello world!

,#+caption: Shell command with stderr
,#+begin_src sh :results output :exports both
  echo "Hello world!"
,#+end_src
#+end_src
```

Thanks again for this lovely package. I use it many times a day.

**Comment by unhammer** [comment]
Good idea! See if https://github.com/unhammer/org-rich-yank/pull/14 fixes it?
