### ISSUE TITLE
copying and pasting from web sources?

### ISSUE THREAD

**Issue by zeltak** [unhammer/org-rich-yank#4]
Sorry for the late reposne (work life et al :))

as discussed would be cool to also apply similar methodology when copying and pasting sections from the web. so that it would paste the text nicely formatted to org with a nice link to the source/URL

best

Z

**Comment by unhammer** [comment]
ba7eb7ba8d25dbf053b1f746061a4442375da437 implements this for `eww` – does that solve it for you? `w3m` should already be supported by org.

I don't think we can do this for browsers outside Emacs – there, I think https://orgmode.org/worg/org-contrib/org-protocol.html is a better method (though I never managed to get that working myself).

**Comment by zeltak** [comment]
thx

yeah i could never get org-prtocol to work on my machine either :) ill try it with eww though ive never used emacs based browsers before :)

best

Z

**Comment by unhammer** [comment]
OK, I'll close this for now, as I think org-protocol is probably the way to go if one wants to copy-paste from web sources. We can re-open if someone who actually uses org-protocol has some issue with org-rich-yank.
