### ISSUE TITLE
[spacemacs] org-rich-yank.elc failed to provide feature ‘org-rich-yank’

### ISSUE THREAD

**Issue by stradicat** [unhammer/org-rich-yank#8]
When starting Emacs with the `spacemacs` configuration that enables `org` functionality, the following error message pops up:

`org-rich-yank.elc failed to provide feature ‘org-rich-yank’`

OS: Ubuntu 18.04 i386
Emacs version: `27.1`
`org-rich-yank` version: `20201115.823`

Let me know what else you'd need to begin pinpointing probable causes.
Cheers!

**Comment by unhammer** [comment]
Strange, we do provide at the bottom of the file
https://github.com/unhammer/org-rich-yank/blob/master/org-rich-yank.el#L138-L160

Could it be an outdated .elc? I don't know how spacemacs layers work, but you could `M-x byte-compile-file` and find org-rich-yank.el to recompile it (if Spacemacs uses elpa, it'll be in something like ~/.emacs.d/elpa/org-rich-yank-VERSION

**Comment by stradicat** [comment]
Thanks for the prompt reply!

I'll test later again; I did preemptively byte-recompile the whole `elpa` directory, but perhaps I should look deeper and specifically at the package file.

Otherwise, if the package is fine (it does work without errors and with the exact same dotfile on Ubuntu 20.04 `amd64`), I'll check with the `spacemacs` folks.

**Comment by stradicat** [comment]
Well, the problem doesn't show up anymore, so I'm closing the issue.
Cheers!
