### ISSUE TITLE
Support for styling link format

### ISSUE THREAD

**Issue by nickanderson** [unhammer/org-rich-yank#9]
The code that I yank and paste with `org-rich-yank` is often destined for others via some export backend (e.g. ox-jira, org-mime, one of the numerous markdown backends for some other random input that accepts markdown). Having the link that jumps back to where the code was pulled from is super convenient, but only for me. The file path is typically a distraction for someone else.  If it's left in the export, it's not correct without some editing. 

I have developed a pattern of prefixing the link with `#+comment: ` so that it's not exported but it's still available for my own use. I think it would be nice to provide some way to customize the format string. Probably I could figure out some type of advice to munge the string automatically but I haven't set out on that adventure yet.

**Comment by nickanderson** [comment]
I put up pr #10 with a naive solution.

**Comment by unhammer** [comment]
Since it's a custom-variable that people might depend on, I prefer a more general solution – does e1566b7d7dd46f04ce08f0f948d108d3d18f4494 work for you @nickanderson ?

**Comment by nickanderson** [comment]
yeah, works great for me. Thanks!
